In [122]:
## NLP: Natural language processing

In [123]:
# Steps for gathering Data:

# 1. public data set
# 2. Web Scraping
# 3. APIs
# 4. Manual Collection
# 5. NLP tools for text augmentation

In [124]:
# Step 2: Text cleaning

# 1. lowercasing
# 2. Remove punctuations
# 3. Remove numbers (optional)
# 4. Remove links
# 5. Remove HTML tags (for web scraping)
# 6. Remove emojis
# 7. Remove common words
# 8. Spelling correction

In [125]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [126]:
df = pd.read_csv("train.txt", sep= ";", header = None, names = ["text", "emotion"])

In [127]:
df.head()

,text,emotion
0,i didnt feel humiliated,sadness
1,i can go from feeling so hopeless to so damned...,sadness
2,im grabbing a minute to post i feel greedy wrong,anger
3,i am ever feeling nostalgic about the fireplac...,love
4,i am feeling grouchy,anger


In [128]:
df.isnull().sum()

,0
text,0
emotion,0


In [129]:
unique_emotions = df["emotion"].unique()
emotion_numbers = {}
i = 0

for emo in unique_emotions:
  emotion_numbers[emo] = i
  i += 1

df["emotion"] = df["emotion"].map(emotion_numbers)

In [130]:
df

,text,emotion
0,i didnt feel humiliated,0
1,i can go from feeling so hopeless to so damned...,0
2,im grabbing a minute to post i feel greedy wrong,1
3,i am ever feeling nostalgic about the fireplac...,2
4,i am feeling grouchy,1
...,...,...
15995,i just had a very brief time in the beanbag an...,0
15996,i am now turning and i feel pathetic that i am...,0
15997,i feel strong and good overall,5
15998,i feel like this was such a rude comment and i...,1


In [131]:
df["text"] = df["text"].apply(lambda x : x.lower()) # lowercasing

In [132]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans("","",string.punctuation))

In [133]:
df["text"].apply(remove_punc)

,text
0,i didnt feel humiliated
1,i can go from feeling so hopeless to so damned...
2,im grabbing a minute to post i feel greedy wrong
3,i am ever feeling nostalgic about the fireplac...
4,i am feeling grouchy
...,...
15995,i just had a very brief time in the beanbag an...
15996,i am now turning and i feel pathetic that i am...
15997,i feel strong and good overall
15998,i feel like this was such a rude comment and i...


In [134]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [135]:
def remove_emojis(txt):
  new = ""
  for i in txt:
    if not i.isascii():
      new += i
  return new
  df["text"] = df["text"].apply(remove_emojis)

In [136]:
print(df["text"].head())

0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy
Name: text, dtype: object


In [137]:
# NLTK: Natural lang toolkit
import nltk

# A collection of text is called a Corpus
# A group of words forming a maningful statement is called a sentence
# Each individual word or symbol in the text is called a token

In [138]:
print(df["text"].head())

0                              i didnt feel humiliated
1    i can go from feeling so hopeless to so damned...
2     im grabbing a minute to post i feel greedy wrong
3    i am ever feeling nostalgic about the fireplac...
4                                 i am feeling grouchy
Name: text, dtype: object


In [139]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [140]:
stop_words = set(stopwords.words("english"))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [141]:
def remove(txt):
    words = str(txt).split()
    cleaned = []

    for i in words:
        if not i in stop_words:
            cleaned.append(i)

    return ' '.join(cleaned)

In [142]:
df["text"] = df["text"].apply(remove)

In [143]:
## BAG OF WORDS vectorization technique

from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range=(2,2)) # Bigrams in sklearn

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("\nBoW Matrix:\n", X.toarray())

Vocabulary: ['is great' 'is the' 'love pasta' 'love pizza' 'pasta is' 'pizza is'
 'the best']

BoW Matrix:
 [[0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1]
 [0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0]]


In [144]:
df.head()

,text,emotion
0,didnt feel humiliated,0
1,go feeling hopeless damned hopeful around some...,0
2,im grabbing minute post feel greedy wrong,1
3,ever feeling nostalgic fireplace know still pr...,2
4,feeling grouchy,1


In [145]:
# This splits your data: 80% for training the model, 20% held back to test how well it generalizes

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [146]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
# CountVectorizer turns each sentence into a vector of word counts (Bag of Words)..

from sklearn.naive_bayes import MultinomialNB
# MultinomialNB is a Naive Bayes classifier well-suited for word count data.
# Trains on the BoW vectors, predicts emotions for the test set.
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
# .fit_transform() on training data: learns the vocabulary AND converts the text.

X_test_bow = bow_vectorizer.transform(X_test)
# .transform() on test data: reuses the same vocabulary.


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))


0.768125


In [148]:
# TfidfVectorizer is like CountVectorizer, but instead of raw counts, it weighs words by how distinctive they are
  #(common words like "the" get down-weighted; rare, meaningful words get boosted)

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
# Same Naive Bayes model, but trained on TF-IDF vectors instead.

nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [149]:
y_pred = nb2_model.predict(X_test_tfidf)

In [150]:
print(accuracy_score(y_test, y_pred))

0.6609375


In [151]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(max_iter=1000)
# max_iter=1000 increases the number of optimization iterations so the model has enough room to converge

logistic_model.fit(X_train_tfidf, y_train)
log_pred = logistic_model.predict(X_test_tfidf)

print(accuracy_score(y_test, log_pred))

0.8628125
